POST http://localhost:5005/settings/create
Content-Type: application/json

{
         "site":  "site",
         "logo" : "logo",
         "favicon" : "favicon",
         "copyright" : "copyright",
         "currency" : "currency",
         "currencycode" : "currencycode",
         "twilotoken" : "twilotoken",
         "twilionumber" : "twilionumber",
         "pub_pub_key" : "pub_sub_key",
         "pub_sub_key" : "pub_sub_key",
         "client_id" : "client_id",
         "client_secret" : "client_secret",
         "default_language" : "default_language",
         "customer_username" : "customer_username",
         "terms_user" : "terms_user",
         "terms_restaurants" : "terms_restaurants",
         "default_location" : "default_location",
         "amount_referral" : "amount_referral",
         "payment" : "payment",
         "stripe_charge" : "stripe_charge",
         "stripe_publish_key" : "stripe_publish_key",
         "stripe_secret" : "stripe_secret",
         "stripe_url" : "stripe_url",
         "productOrder" : "productOrder",
         "dispute_responsetime" : "dispute_responsetime",
         "search_distance" : "search_distance",
         "deliveryman_responsetime" : "deliveryman_responsetime",
         "dish_commission" : "dish_commission",
         "delivery_fee" : "delivery_fee",
         "orderlimit_min" : "orderlimit_min",
         "orderlimit_max" : "orderlimit_max",
         "order_assinged" : "order_assinged",
         "android_env" : "android_env",
         "android_pushkey" : "android_pushkey",
         "ios_user_env" : "ios_user_env",
         "ios_provider_env" : "ios_provider_env",
         "android_applink" : "android_applink",
         "os_applink" : "os_applink",
         "iosprovider_pushpassword" : "iosprovider_pushpassword",
         "iosshop_env" : "iosshop_env",
         "iosshop_pushpassword" : "iosshop_pushpassword",
         "iosuser_pushpassword" : "iosuser_pushpassword",
         "iosuser_topic" : "iosuser_topic",
         "iosuser_apppassword" : "iosuser_apppassword",
         "iosprovider_apptopic" : "iosprovider_apptopic",
         "iosprovider_apppassword" : "iosprovider_apppassword",
         "iosshop_apptopic" : "iosshop_apptopic",
         "iosshop_apppassword" : "iosshop_apppassword",
         "googlemap_key" : "googlemap_key",
         "twilio_sid" : "twilio_sid",
         "twilio_token" : "twilio_token",
         "twilio_number" : "twilio_number",
         "fb_client_id" : "fb_client_id",
         "fb_client_secret" : "fb_client_secret",
         "fb_redirect" : "fb_redirect",
         "google_client_id" : "google_client_id",
         "google_client_secret" : "google_client_secret",
         "google_redirect" : "google_redirect",
         "facebook" : "facebook",
         "instagram" : "instagram",
         "pinterest" : "pinterest",
         "vimeo" : "vimeo",
         "youtube" : "youtube",
         "is_sociallogin" : "is_sociallogin"
}